feat(template): add checkmate template
Dokploy/dokploy pull request #1033
Opened 2024-12-30 15:09 UTC by DJKnaeckebrot

Added [Checkmate](https://bluewavelabs.gitbook.io/checkmate) template

2024-12-30 15:12 UTC, DJKnaeckebrot commented
@Siumauricio I can't set a specific version as they only push latest images to docker hub

2025-01-02 00:57 UTC, Siumauricio requested changes

2025-01-02 00:57 UTC, Siumauricio commented on apps/dokploy/templates/checkmate/docker-compose.yml
> +      - ./redis/data:/data
```suggestion
    volumes:
      - ../files/redis/data:/data
```

2025-01-02 00:57 UTC, Siumauricio commented on apps/dokploy/templates/checkmate/docker-compose.yml
> +      - ./mongo/data:/data/db
```suggestion
      - ../files/mongo/data:/data/db
```

2025-01-02 00:57 UTC, merged