feat: huly template
Dokploy/dokploy pull request #376
Opened 2024-08-25 16:40 UTC by bhaleraosaurabh

1. Added template for huly
2. Updated docs to add huly in templates section

https://github.com/user-attachments/assets/82d091ba-0f6e-4b36-85e4-f4333e5ab727

2024-08-26 03:26 UTC, Siumauricio requested changes

2024-08-26 03:26 UTC, Siumauricio commented on apps/dokploy/templates/huly/docker-compose.yml
> +      - 27017:27017
is not necessary to expose the ports to the host, remove this

2024-08-26 03:26 UTC, Siumauricio commented on apps/dokploy/templates/huly/docker-compose.yml
> +      - 9001:9001
is not necessary to expose the ports to the host, remove this

2024-08-26 03:26 UTC, Siumauricio commented on apps/dokploy/templates/huly/docker-compose.yml
> +      - 3001:3001
is not necessary to expose the ports to the host, remove this

2024-08-26 03:26 UTC, Siumauricio commented on apps/dokploy/templates/huly/docker-compose.yml
> +    ports:
is not necessary to expose the ports to the host, remove this

2024-08-26 03:26 UTC, Siumauricio commented on apps/dokploy/templates/huly/docker-compose.yml
> +      - 3078:3078
is not necessary to expose the ports to the host, remove this

2024-08-26 03:26 UTC, Siumauricio commented on apps/dokploy/templates/huly/docker-compose.yml
> +      - 8087:8080
is not necessary to expose the ports to the host, remove this

2024-08-26 03:26 UTC, Siumauricio commented on apps/dokploy/templates/huly/docker-compose.yml
> +      - dokploy-network
is not necessary to add the dokploy network, when you assign a domain to a service it automatically will add this network

2024-08-26 03:26 UTC, Siumauricio commented on apps/dokploy/templates/huly/docker-compose.yml
> +      - dokploy-network
is not necessary to add the dokploy network, when you assign a domain to a service it automatically will add this network

2024-08-26 03:26 UTC, Siumauricio commented on apps/dokploy/templates/huly/docker-compose.yml
> +      - dokploy-network
is not necessary to add the dokploy network, when you assign a domain to a service it automatically will add this network

2024-08-26 03:26 UTC, Siumauricio commented on apps/dokploy/templates/huly/docker-compose.yml
> +      - dokploy-network
is not necessary to add the dokploy network, when you assign a domain to a service it automatically will add this network

2024-08-26 03:26 UTC, Siumauricio commented on apps/dokploy/templates/huly/docker-compose.yml
> +      - dokploy-network
is not necessary to add the dokploy network, when you assign a domain to a service it automatically will add this network

2024-09-01 16:42 UTC, bhaleraosaurabh commented
Facing issues as there are issues connecting to the application after resolving the PR comments. I'll re-raise the PR once it's fixed

2024-09-01 16:42 UTC, closed without merging