feat: add tolgee template
Dokploy/dokploy pull request #601
Opened 2024-10-26 18:26 UTC by CodeWithKamal

This PR adds a new template for Tolgee. The template has been tested and works with Traefik for routing. Also, added appropriate environment configurations for Docker.

2024-10-26 18:39 UTC, CodeWithKamal commented
### Steps to use the template:

1. Deploy the template
2. Wait for few minutes for Tolgee to boot up.
3. Goto the `TOLGEE_HOST` value
4. Login with username/email: `admin` and password: `admin`

There you go!

2024-10-27 08:31 UTC, Siumauricio approved these changes

2024-10-27 08:31 UTC, Siumauricio commented on apps/dokploy/templates/tolgee/docker-compose.yml
> +      - '8080:8080'
Can you leave as `8080`

2024-10-27 08:31 UTC, Siumauricio requested changes
The Templates works fine, just review the comments

Thanks!

2024-10-27 08:34 UTC, CodeWithKamal commented on apps/dokploy/templates/tolgee/docker-compose.yml
> +      - '8080:8080'
so like this?

```
ports:
    - '8080'
```

2024-10-27 08:38 UTC, Siumauricio commented on apps/dokploy/templates/tolgee/docker-compose.yml
> +      - '8080:8080'
Yes!

2024-10-27 08:44 UTC, CodeWithKamal commented
done!

2024-10-27 08:45 UTC, Siumauricio approved these changes
Thanks!

2024-10-27 08:49 UTC, Siumauricio commented
run `pnpm check` to format all the files

2024-10-27 08:50 UTC, CodeWithKamal commented
what should I do now ?

2024-10-27 08:52 UTC, Siumauricio commented
Fixed, just ran again `pnpm check`

2024-10-27 08:59 UTC, CodeWithKamal commented
done, fixed the lint issue.

2024-10-27 09:25 UTC, Siumauricio approved these changes

2024-10-27 16:18 UTC, merged