feat: add nextcloud-aio template
Dokploy/dokploy pull request #705
Opened 2024-11-14 15:16 UTC by seppulcro

Hi, this PR should add Nextcloud AIO using the community maintaned https://github.com/nextcloud/docker docker image.

2024-11-15 06:39 UTC, Siumauricio requested changes

2024-11-15 06:39 UTC, Siumauricio commented on apps/dokploy/templates/nextcloud-aio/index.ts
> +		"NEXTCLOUD_DOMAIN=mynextclouddomain.tld",
why not use the randomDomain here?

2024-11-15 09:06 UTC, seppulcro commented on apps/dokploy/templates/nextcloud-aio/index.ts
> +		"NEXTCLOUD_DOMAIN=mynextclouddomain.tld",
You're 100% correct this was an oversight on my end, sorry for that.
I'll update this to use the `utils` correctly.

Should be fixed by latest commit :)

2024-11-17 15:53 UTC, Siumauricio approved these changes
Thanks

2024-11-17 15:53 UTC, merged