feat: add russian translation init
Dokploy/dokploy pull request #723
Opened 2024-11-18 08:50 UTC by WoWnik

2024-11-18 13:14 UTC, TheLetslook commented
@Siumauricio I can confirm that it looks correct

2024-11-18 20:14 UTC, VladTheCow requested changes

2024-11-18 20:14 UTC, VladTheCow commented on apps/dokploy/public/locales/ru/settings.json
> +	"settings.server.webServer.storage.cleanAll": "Очистить всё",
```suggestion
	"settings.server.webServer.storage.cleanAll": "Очистить все",
```
😭

2024-11-18 20:56 UTC, WoWnik commented on apps/dokploy/public/locales/ru/settings.json
> +	"settings.server.webServer.storage.cleanAll": "Очистить всё",
А в слове "тёмная" ничего не смущает?)

2024-11-19 15:45 UTC, TheLetslook requested changes
I don't think it's necessary, but languages are usually sorted alphabetically

2024-11-19 15:45 UTC, TheLetslook commented on apps/dokploy/components/dashboard/settings/appearance-form.tsx
> +	language: z.enum(["en", "pl", "zh-Hans", "ru"], {
```suggestion
	language: z.enum(["en", "pl", "ru", "zh-Hans"], {
```

2024-11-19 15:45 UTC, TheLetslook commented on apps/dokploy/components/dashboard/settings/appearance-form.tsx
> +													{ label: "Русский", value: "ru" },
```suggestion
													{ label: "English", value: "en" },
													{ label: "Polski", value: "pl" },
													{ label: "Русский", value: "ru" },
													{ label: "简体中文", value: "zh-Hans" },
```

2024-11-19 15:45 UTC, TheLetslook commented on apps/dokploy/next-i18next.config.cjs
> +		locales: ["en", "pl", "zh-Hans", "ru"],
```suggestion
		locales: ["en", "pl", "ru", "zh-Hans"],
```

2024-11-19 15:45 UTC, TheLetslook commented on apps/dokploy/pages/_app.tsx
> +				locales: ["en", "pl", "zh-Hans", "ru"],
```suggestion
				locales: ["en", "pl", "ru", "zh-Hans"],
```

2024-11-19 15:45 UTC, TheLetslook commented on apps/dokploy/utils/hooks/use-locale.ts
> +const SUPPORTED_LOCALES = ["en", "pl", "zh-Hans", "ru"] as const;
```suggestion
const SUPPORTED_LOCALES = ["en", "pl", "ru", "zh-Hans"] as const;
```

2024-11-19 15:54 UTC, WoWnik commented on apps/dokploy/components/dashboard/settings/appearance-form.tsx
> +	language: z.enum(["en", "pl", "zh-Hans", "ru"], {
done

2024-11-19 15:54 UTC, WoWnik commented on apps/dokploy/components/dashboard/settings/appearance-form.tsx
> +													{ label: "Русский", value: "ru" },
done

2024-11-19 15:54 UTC, WoWnik commented on apps/dokploy/next-i18next.config.cjs
> +		locales: ["en", "pl", "zh-Hans", "ru"],
done

2024-11-19 15:54 UTC, WoWnik commented on apps/dokploy/pages/_app.tsx
> +				locales: ["en", "pl", "zh-Hans", "ru"],
done

2024-11-19 15:54 UTC, WoWnik commented on apps/dokploy/utils/hooks/use-locale.ts
> +const SUPPORTED_LOCALES = ["en", "pl", "zh-Hans", "ru"] as const;
done

2024-11-19 19:06 UTC, vladflotsky commented on apps/dokploy/public/locales/ru/settings.json
> +	"settings.server.webServer.storage.cleanAll": "Очистить всё",
Не заметил) Я бы заменил букву ё на е, никто ее не использует

2024-11-19 21:01 UTC, WoWnik commented on apps/dokploy/public/locales/ru/settings.json
> +	"settings.server.webServer.storage.cleanAll": "Очистить всё",
Заменил везде

2024-11-20 02:12 UTC, merged