fix: stirling docker compose
Dokploy/dokploy pull request #743
Opened 2024-11-20 21:48 UTC by jujur10

Fixing the issue with stirling when trying to deploy.
In this merge request I am just transposing the docker compose example from [Stirling documentation](https://docs.stirlingpdf.com/Getting%20started/Installation/Docker/Docker%20Install)
#742

2024-11-21 06:27 UTC, Siumauricio requested changes

2024-11-21 06:27 UTC, Siumauricio commented on apps/dokploy/templates/stirling/docker-compose.yml
> +      - '8080:8080'
```suggestion
      - 8080
```

2024-11-21 06:27 UTC, Siumauricio commented on apps/dokploy/templates/stirling/docker-compose.yml
> +      - ./StirlingPDF/pipeline:/pipeline/
use volumes please instead of binding the folders

like 

```yaml
- stirling_pdf_trainingdata:/usr/share/tessdata
```

2024-11-21 07:19 UTC, jujur10 commented
I've modified it, let me know if it's ok for you.  :+1:

2024-11-22 06:38 UTC, Siumauricio approved these changes
Thanks!

2024-11-22 06:38 UTC, merged