feat: add ontime template
Dokploy/dokploy pull request #760
Opened 2024-11-25 12:13 UTC by henriklovhaug

2024-11-27 04:25 UTC, Siumauricio requested changes

2024-11-27 04:25 UTC, Siumauricio commented on apps/dokploy/templates/ontime/docker-compose.yml
> +      - 9999
```suggestion
    ports:
      - 4001
      - 8888
      - 9999
```

2024-11-27 04:26 UTC, merged

2024-11-27 07:57 UTC, henriklovhaug commented
Quick question, why add ports and not just expose? Traefik is able to route to the service with expose since it is in the same Docker network.

2024-11-28 13:29 UTC, beratcmn commented
I am on 0.12 but Dokploy can't find the 0.13.0 update when I use "Check Updates"