Added German Readme
Dokploy/dokploy pull request #83
Opened 2024-05-14 10:32 UTC by DontFred

2024-05-14 10:38 UTC, DontFred commented
Maybe you could change the documentation to an open source project as well.  Then we could help you to maintain it. Possible is to use [nextra](https://nextra.site/) with markdown.

2024-05-14 19:52 UTC, Siumauricio commented on README-de.md
> +## 🌟 Features
Change to a german language

2024-05-14 19:53 UTC, Siumauricio requested changes
please update the titles to a german language

2024-05-14 19:53 UTC, Siumauricio commented on README-de.md
> +## Explanation
Change to a german language

2024-05-14 19:53 UTC, Siumauricio commented on README-de.md
> +## 🌟 Features
Change to a german language

2024-05-14 19:53 UTC, Siumauricio commented on README-de.md
> +## 📄 Documentation
Change to a german language

2024-05-14 19:53 UTC, Siumauricio commented on README-de.md
> +## 🚀 Getting Started
Change to a german language

2024-05-15 07:29 UTC, Siumauricio approved these changes
Thanks!

2024-05-15 07:29 UTC, merged