fix: dashboard layout styles
Dokploy/dokploy pull request #86
Opened 2024-05-15 04:47 UTC by hehehai

- [x] Dashboard layout scroll
- [x] Dashboard nav
- [x] Code input font

2024-05-15 05:02 UTC, hehehai commented
https://github.com/Dokploy/dokploy/assets/12692552/7047b050-b9ee-4d4a-b8b6-bb9023ab0cdb

2024-05-15 19:50 UTC, DontFred reviewed
framer-motion is a realy heavy package to add two animations, maybe just use tailwind-animation e. g. [tailwind-animate](https://github.com/jamiebuilds/tailwindcss-animate)

2024-05-16 04:15 UTC, Siumauricio requested changes
Can you please also  check the font is not being applied in some places, example the modals, dropdowns, titles and this happen in almost every screen

![image](https://github.com/Dokploy/dokploy/assets/47042324/bae7bbd6-d63e-441e-bb78-bfce6f3a5f32)

![image](https://github.com/Dokploy/dokploy/assets/47042324/5fa2856c-683c-4f6f-853b-046c9cbe0b98)

![image](https://github.com/Dokploy/dokploy/assets/47042324/7818425b-b180-48d6-bd09-884571eb55df)

![image](https://github.com/Dokploy/dokploy/assets/47042324/d3ab2433-8928-4c1b-9fa6-98a29c9f48c0)


![image](https://github.com/Dokploy/dokploy/assets/47042324/08f87f65-18f6-44d7-94c6-361c5f10b0f8)

2024-05-16 04:15 UTC, Siumauricio commented on components/layouts/navigation-tabs.tsx
> +										)}
using framer-motion for this case Is innecesary because is really is heavier, I'm pretty sure we can achieve the same animation with some js-css tricks.

2024-05-16 04:15 UTC, Siumauricio commented on components/shared/status-tooltip.tsx
> +						<div className={cn("size-3.5 rounded-full bg-teal-400", className)} />
The bg-card color is perceived better in an idle state than a high contrast color

2024-05-16 04:15 UTC, Siumauricio commented on pages/_app.tsx
> +    <main className={`${inter.variable} font-sans`}>
wrap the classname with `cn()` utility

2024-05-16 04:15 UTC, Siumauricio commented on components/ui/file-tree.tsx
By some reasson but the file tree responsive is not working on mobile, probably this can be caused by the font or something else 


This is how it looks in production:

![image](https://github.com/Dokploy/dokploy/assets/47042324/969c10f9-91d1-4b83-a5b9-b40494870b2a)



This is how looks with your changes
![image](https://github.com/Dokploy/dokploy/assets/47042324/1828b7ab-5209-4b50-b68b-efc8ccba13f4)

2024-05-16 04:15 UTC, Siumauricio commented on components/layouts/navigation-tabs.tsx
> +												<div className="w-full h-full rounded-md bg-zinc-100 dark:bg-zinc-800" />
The animation makes more sense on desktop, in mobile we can avoid this animation

2024-05-16 04:15 UTC, Siumauricio commented on components/layouts/navigation-tabs.tsx
> +											>
And i think the animation we want to achieve could something similar to this 

https://github.com/Dokploy/dokploy/assets/47042324/dcfbf056-16f3-4b86-a86b-1e76008ad63a

And mobile:

https://github.com/Dokploy/dokploy/assets/47042324/f009324e-fbe4-4ba1-ba2d-d4ce7d05173b

2024-05-16 13:43 UTC, hehehai commented on components/shared/status-tooltip.tsx
> +						<div className={cn("size-3.5 rounded-full bg-teal-400", className)} />
<img width="1378" alt="image" src="https://github.com/Dokploy/dokploy/assets/12692552/f934dac7-5591-40c1-b17f-be3e6bc9396f">
`bg-card` But this is white

2024-05-16 15:25 UTC, hehehai commented
@Siumauricio @DontFred In fact, framer-motion does not affect much performance, and for a background application, many OSS use this package.

2024-05-16 20:31 UTC, DontFred commented
@hehehai framer-motion is a super package don't get me wrong, but just to add one animation `2.24 MB` package is unnecessary. Maybe in the future when using not just one animation.

2024-05-17 04:49 UTC, Siumauricio requested changes

2024-05-17 04:49 UTC, Siumauricio commented on components/shared/status-tooltip.tsx
> +						<div className={cn("size-3.5 rounded-full bg-teal-400", className)} />
Got it that only happens on light mode, so let's apply this `bg-muted-foreground dark:bg-card`

2024-05-17 04:49 UTC, Siumauricio commented on components/dashboard/docker/logs/docker-logs-id.tsx
>  		</div>
Can you check please the colors of the terminal? currently in light mode it looks white and it have very low contrast

![Screenshot 2024-05-16 at 10 44 36 PM](https://github.com/Dokploy/dokploy/assets/47042324/0e79c1fc-6248-4e9a-a51d-60a6e452e6bd)
![Screenshot 2024-05-16 at 10 48 26 PM](https://github.com/Dokploy/dokploy/assets/47042324/6797c374-7874-4472-87fd-39c41e8d1c27)

2024-05-18 03:43 UTC, Siumauricio approved these changes
Thank you!!

2024-05-18 03:43 UTC, merged