feat: add unsend template
Dokploy/dokploy pull request #869
Opened 2024-12-12 15:47 UTC by DJKnaeckebrot

Adding Unsend Template

2024-12-12 16:25 UTC, DJKnaeckebrot commented
I just saw that if reformatted the whole files spacing :( I'll try to fix that

2024-12-13 06:49 UTC, Siumauricio requested changes

2024-12-13 06:49 UTC, Siumauricio commented on apps/dokploy/templates/unsend/docker-compose.yml
> +    container_name: unsend-db-prod
```suggestion
  unsend-db-prod:
    image: postgres:16
    networks:
      - dokploy-network
```

2024-12-13 06:49 UTC, Siumauricio commented on apps/dokploy/templates/unsend/docker-compose.yml
> +    container_name: unsend-redis-prod
```suggestion
  unsend-redis-prod:
    image: redis:7
    networks:
      - dokploy-network
```

2024-12-13 06:49 UTC, Siumauricio commented on apps/dokploy/templates/unsend/docker-compose.yml
> +    container_name: unsend-storage-prod
```suggestion
  unsend-storage-prod:
    image: minio/minio
    networks:
      - dokploy-network
```

2024-12-13 06:49 UTC, Siumauricio commented on apps/dokploy/templates/unsend/docker-compose.yml
> +    container_name: unsend
```suggestion
  unsend:
    image: unsend/unsend:latest
    networks:
      - dokploy-network
```

2024-12-13 06:49 UTC, Siumauricio commented on apps/dokploy/templates/unsend/docker-compose.yml
> +      postgres:
```suggestion
      unsend-db-prod:
```

2024-12-13 06:49 UTC, Siumauricio commented on apps/dokploy/templates/unsend/docker-compose.yml
> +      redis:
```suggestion
      unsend-redis-prod:
```

2024-12-13 06:49 UTC, Siumauricio commented on apps/dokploy/templates/unsend/index.ts
> +    "AWS_ACCESS_KEY=",
```suggestion
    "GITHUB_ID='Fill'",
    "GITHUB_SECRET='Fill'",
    "AWS_DEFAULT_REGION=us-east-1",
    "AWS_SECRET_KEY='Fill'",
    "AWS_ACCESS_KEY='Fill'",
```

2024-12-13 06:53 UTC, Siumauricio requested changes

2024-12-13 06:53 UTC, Siumauricio commented on apps/dokploy/templates/unsend/docker-compose.yml
> +    image: unsend/unsend:latest
can you use a defined version and not the latest?

2024-12-13 06:53 UTC, Siumauricio commented on apps/dokploy/templates/unsend/docker-compose.yml
> +    image: minio/minio
can you use a defined version?

2024-12-14 07:24 UTC, Siumauricio approved these changes
Thanks!

2024-12-14 07:24 UTC, merged