Fix - Update version Ollama and WebUI
Dokploy/dokploy pull request #905
Opened 2024-12-16 10:41 UTC by erickgonz

2024-12-16 17:42 UTC, drudge requested changes
When updating the versions, make sure you make the`templates.ts` match:
https://github.com/Dokploy/dokploy/blob/829aa2a63cb3268360e5802bc0d2c67b572134eb/apps/dokploy/templates/templates.ts#L353

2024-12-18 05:53 UTC, Siumauricio requested changes

2024-12-18 05:53 UTC, Siumauricio commented on apps/dokploy/templates/open-webui/index.ts
> +		`HASH=${mainServiceHash}`,
What's the purpose of this hash?

2024-12-18 05:54 UTC, Siumauricio commented
Did you tested this?

![image](https://github.com/user-attachments/assets/c32b61c3-af80-4898-9f93-f2f94111fdff)

2025-01-11 23:31 UTC, Siumauricio commented
Feel free to reopen!

2025-01-11 23:31 UTC, closed without merging

2025-03-04 06:52 UTC, arthrod commented
Isn't 8080 just the backend?