fix: docker registry URL if provided
Dokploy/dokploy pull request #918
Opened 2024-12-17 10:11 UTC by guotingchao

- Updated logic to include registry URL if provided

👋 Hi, This PR solved a problem for me and another brother @Hundred-Killer, in some countries or network situation, we can only use similar self-hosted Docker image service, I used Github Action to implement the packaging and push to my own private image, when I use register url to implement docker deployment, I always get some errors.

This issue has been discussed on Discord and Issue as follows:

Issues: [custom image registry dont work #902](https://github.com/Dokploy/dokploy/issues/902)
Discord Help Post:  [Deployment Docker Register Url is not expected](https://discord.com/channels/1234073262418563112/1318099944762245171)

2024-12-18 05:47 UTC, Siumauricio commented
I think this change does not solve the problem of the original issue, nor do I see much sense in adding the registryURL as a prefix to the initial image, 

Did you tested this?

2024-12-18 07:28 UTC, guotingchao commented
> I think this change does not solve the problem of the original issue, nor do I see much sense in adding the registryURL as a prefix to the initial image,
> 
> Did you tested this?

I tested it, and after modifying it to fix my original problem, I was able to pull in my private image and log into the correct register URL without any problems!

2024-12-18 22:29 UTC, drudge requested changes
This won't solve your issue, but #937 will.

2024-12-19 09:51 UTC, guotingchao commented
> This won't solve your issue, but #937 will.
Yes , I checked the code and it does handle it much better, any plans to release a new version today.

2024-12-19 09:52 UTC, guotingchao commented
Since that is the case, we can close this pull request.

2024-12-19 09:52 UTC, closed without merging