Added onedev docker compose
Dokploy/dokploy pull request #925
Opened 2024-12-17 15:23 UTC by mohabgabber

Added onedev docker-compose and index.ts files, as indicated by the official onedev documentation: https://docs.onedev.io/installation-guide/run-as-docker-container

2024-12-17 16:28 UTC, drudge requested changes
The template needs to be added to the `templates.ts` file.

2024-12-17 16:52 UTC, mohabgabber commented
> The template needs to be added to the `templates.ts` file.

Done

2024-12-18 05:47 UTC, Siumauricio requested changes

2024-12-18 05:47 UTC, Siumauricio commented on apps/dokploy/templates/onedev/docker-compose.yml
> +    container_name: onedev
```suggestion
```

2024-12-18 05:50 UTC, merged